import type { Collection, ContentFile, Manifest } from './types';

// Generated by `npm run content` (git-ignored). Each file becomes its own lazy chunk.
const files = import.meta.glob<ContentFile>('./generated/*/*.json', { import: 'default' });
const manifestLoader = import.meta.glob<Manifest>('./generated/manifest.json', { import: 'default' });

export function loadManifest(): Promise<Manifest> {
  const load = manifestLoader['./generated/manifest.json'];
  if (!load) return Promise.reject(new Error('Generated content is missing. Run `npm run content`.'));
  return load();
}

export function loadContentFile(collection: Collection, chapter: string): Promise<ContentFile> {
  const load = files[`./generated/${collection}/${chapter}.json`];
  if (!load) return Promise.reject(new Error(`No generated content for ${collection}/${chapter}`));
  return load();
}
